# Generated by Django 4.2.3 on 2023-07-11 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='catergory',
            new_name='category',
        ),
    ]
